'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LaborManagement

    '''<summary>
    '''ddlEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEmployee As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTaskDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTaskDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtScheduledDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtScheduledDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateTask As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CreateStatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateStatusLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TaskGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TaskGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ddlPerformanceEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPerformanceEmployee As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtTasksCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTasksCompleted As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProductivityRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductivityRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnLogPerformance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogPerformance As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PerformanceStatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PerformanceStatusLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PerformanceGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PerformanceGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ddlComplianceEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlComplianceEmployee As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtHoursWorked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHoursWorked As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnLogCompliance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogCompliance As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ComplianceStatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComplianceStatusLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ComplianceGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComplianceGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''RefreshButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RefreshButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''StatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLabel As Global.System.Web.UI.WebControls.Label
End Class
