'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TransportManagement

    '''<summary>
    '''txtOrigin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrigin As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDestination As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDistance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDistance As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEstimatedTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEstimatedTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCreateRoute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateRoute As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RouteStatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RouteStatusLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RouteGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RouteGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ddlVehicle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVehicle As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCurrentLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCurrentLocation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlShipmentStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlShipmentStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCreateShipment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateShipment As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ShipmentStatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipmentStatusLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShipmentGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipmentGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtVehicleID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVehicleID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDriverName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDriverName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSchedule As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFuelCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFuelCost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCreateResource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateResource As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ResourceStatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResourceStatusLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ResourceGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResourceGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''RefreshButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RefreshButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''StatusLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusLabel As Global.System.Web.UI.WebControls.Label
End Class
